# data-raw/make_test_fixtures.R
# Run ONCE, offline, with the real embedders installed. Commits:
#   tests/testthat/fixtures/corpus.rds              ~15 sentences, labelled pos/neg/neutral
#   tests/testthat/fixtures/emb_<backend>.rds       native-dim embedding matrix per backend
#   tests/testthat/fixtures/scores_<backend>_xgb.rds golden scores from the CURRENT scorer
#   tests/testthat/fixtures/emb_e5-small_prefixed.rds    embed of "query: I love this"
#   tests/testthat/fixtures/emb_e5-small_unprefixed.rds  embed of "I love this"
#   tests/testthat/fixtures/PROVENANCE.md           HF revision hashes + neutral_band source
# These are the regression anchors; the test run NEVER re-derives them.
#
# NOT part of R CMD check. Do not call from a test. Requires a live embedder
# (sentence-transformers for e5, OPENAI_API_KEY for the openai backend) and the
# packaged xgb scorers (e5-small.xgb / e5-base.xgb in inst/scoring/xgb/1.0/).

library(sentiment.ai)

fixt <- "tests/testthat/fixtures"
dir.create(fixt, showWarnings = FALSE, recursive = TRUE)

corpus <- data.frame(
  text  = c(
    # clear positive
    "I love this, it is absolutely wonderful",
    "Fantastic service and the staff were so kind",
    "Best purchase I have made all year",
    "This made me so happy, highly recommend",
    "Brilliant, exceeded every expectation",
    # clear negative
    "This is terrible and a complete waste of money",
    "Awful experience, I want a refund",
    "The worst product I have ever used",
    "Deeply disappointed, would not recommend",
    "Broken on arrival and support ignored me",
    # genuinely neutral (the rows that matter for the neutral band)
    "The package arrived on Tuesday afternoon",
    "It is a blue rectangular box with a lid",
    "The meeting is scheduled for 3pm",
    "The document has twelve pages",
    "The store opens at nine in the morning"
  ),
  label = c(rep("positive", 5), rep("negative", 5), rep("neutral", 5)),
  stringsAsFactors = FALSE
)
saveRDS(corpus, file.path(fixt, "corpus.rds"))

for (backend in c("e5-small", "e5-base", "text-embedding-3-small")) {
  init_sentiment.ai(model = backend)                  # real embedder (prefix injected internally)
  emb <- embed_text(corpus$text, model = backend)     # native dim: 384 / 768 / 1536
  saveRDS(emb, file.path(fixt, sprintf("emb_%s.rds", backend)))
  scores <- sentiment_score(emb, model = backend)     # CURRENT scorer = the golden anchor
  saveRDS(scores, file.path(fixt, sprintf("scores_%s_xgb.rds", backend)))
}

# Prefix-on vs prefix-off pair for the e5 KNOWN-STRING regression. Bypass the
# internal prefixer by hitting the raw embedder closure directly so we capture
# BOTH the prefixed and un-prefixed embedding of the same sentence.
init_sentiment.ai(model = "e5-small")
raw_embed <- sentiment.env$embed
emb_pre <- t(as.matrix(raw_embed("query: I love this")))
emb_raw <- t(as.matrix(raw_embed("I love this")))
saveRDS(emb_pre, file.path(fixt, "emb_e5-small_prefixed.rds"))
saveRDS(emb_raw, file.path(fixt, "emb_e5-small_unprefixed.rds"))

# PROVENANCE.md: fill from the training repo's eval. DO NOT invent the band here.
# Record one line:  neutral_band: 0.NN   (taken from the training-repo neutral eval)
# plus the HuggingFace revision hash per model so the embeddings are reproducible.
cat(
  "# Fixture provenance\n\n",
  "Generated by data-raw/make_test_fixtures.R on ", as.character(Sys.Date()), "\n\n",
  "## HuggingFace revisions (fill in from the resolved snapshot)\n",
  "intfloat/multilingual-e5-small: <rev>\n",
  "intfloat/multilingual-e5-base:  <rev>\n\n",
  "## OpenAI model\n",
  "text-embedding-3-small: API (no local revision)\n\n",
  "## Neutral band (READ from the training-repo eval, do not invent)\n",
  "neutral_band: <fill from training-repo neutral eval>\n",
  sep = "", file = file.path(fixt, "PROVENANCE.md")
)
